export const LAY_DANH_SACH_PHIM_ACTION = "LAY_DANH_SACH_PHIM_ACTION";

export const LAY_CHI_TIET_PHIM = "LAY_CHI_TIET_PHIM";

export const LAY_THONG_TIN_PHONG_VE = "LAY_THONG_TIN_PHONG_VE";

export const LAY_THONG_TIN_HE_THONG_RAP = "LAY_THONG_TIN_HE_THONG_RAP";

export const lAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP = "lAY_THONG_TIN_LICH_CHIEU_HE_THONG_RAP";

export const lAY_THONG_TIN_PHONG_VE = "LAY_THONG_TIN_PHONG_VE";  
