export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const THEM_NGUOI_DUNG = "THEM_NGUOI_DUNG";
export const XOA_NGUOI_DUNG = "XOA_NGUOI_DUNG";
export const LAY_THONG_TIN_NGUOI_DUNG = "LAY_THONG_TIN_NGUOI_DUNG";
export const CAP_NHAT_USER_ADMIN = "CAP_NHAT_USER_ADMIN";
